// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqqrsuvzxfsogknjuoun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcXJzdXZ6eGZzb2drbmp1b3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzEzMzcsImV4cCI6MjA3MTEwNzMzN30.po_oJVDqnFpC-jIf1qeXmgdFipV6-tp-7JesIABwxuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});